const GRID_COLS		= 6;
const GRID_ROWS		= 5;
const GRID_LEFT		= 800;
const GRID_TOP		= 380;
const CELL_WIDTH	= 160;
const CELL_HEIGHT	= 124;
const CELL_WPAD		= 4;
const CELL_HPAD		= 4;

export {
	GRID_COLS,
	GRID_ROWS,
	GRID_LEFT,
	GRID_TOP,
	CELL_WIDTH,
	CELL_HEIGHT,
	CELL_WPAD,
	CELL_HPAD,
};